import type { Metadata } from "next";
import "../styles/globals.css";
import Header from "@/components/Header";
import Sidebar from "@/components/Sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="flex w-full">
          <Sidebar />
          <div className="flex flex-col w-full">
            <Header />
            <main>
              <div className="flex flex-col w-full">{children}</div>
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}
